apiVersion: v1
kind: Pod
metadata:
  name: quote
  namespace: kiada
spec:
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - name: quote-writer
    image: selgho/quote-writer:0.1.1
    volumeMounts:
    - name: shared
      mountPath: /var/local/output
  - name: nginx
    image: nginx:alpine
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: shared
      mountPath: /usr/share/nginx/html
    lifecycle:
      preStop:
        exec:
          command:
          - nginx
          - -s
          - quit